### PR TITLE
quick fix normalize geometry

### PR DESCRIPTION
**Pull request by mpayson**
Quick fix to the normalizeGeometry function in options.js

I've been working with [Koop](http://koopjs.github.io/) and was encountering a `500 internal server` error when the query geometry's `xmin` equaled 0. I think this is because `xmin` is used to check if the geometry is an envelope and 0 is "falsey" so the query options didn't enter the proper block. Updated so that when xmin=0 `transformEnvelope` is still called.

Wasn't sure how to create a test, but this fixed the issue in my project and all tests are still passing.

Thanks @jgravois for pointing me here!

### CODE REVIEW

**Comment by jgravois** [comment]
try tweaking the test below from [`/test/filter.js`](https://github.com/FeatureServer/winnow/blob/565af94a01c442f1d0907b16f71702e707007af8/test/filter.js#L158-L168)

```js
test('Without a spatialReference property on an Esri-style Envelope', t => {
  const options = {
    geometry: {
      xmin: -118.18055376275225,
      ymin: 34.14141744789609,
      xmax: -118.07069048150241,
      ymax: 34.162726215637875
    }
  }
  run('trees', options, 29744, t)
})
```
if you can use that example to create a new test that only passes as a result of your new patch :1st_place_medal:

**Comment by mpayson** [comment]
@jgravois looks like I may be going down the wrong path? two important notes:

1) realized I'm using an older version in Koop and that the following throws an error... 
```javascript
function normalizeGeometry (options) {
//...
  if (Array.isArray(geometry)) {
    geometry = transformArray(geometry)
  } else if (geometry.xmin) {
    geometry = transformEnvelope(geometry)
  }
//...
  if (inSR) { geometry.coordinates = projectCoordinates(inSR, geometry.coordinates) }
  return geometry
}
```
here my `geometry.coordinates` is undefined, which causes `projectCoordinates` to throw an error. I was circumventing this with my PR by allowing the geometry to enter `transformEnvelope` which defined the `coordinates`. This created the desired results in my app but I'm not sure if this is desired behavior.

 In the latest version of winnow, however, projectCoordinates has been redefined and it's no longer throwing, so part 2...

2) I wrote a test for the current version of winnow that I would expect to work but it's not? (with or without my PR). the test is
```javascript
test('With an esri style envelope and xmin=0', t => {
  const options = {
    outSr: 4326,
    inSr: 4326,
    geometry: {
      xmin: 0,
      ymin: 40,
      xmax: 90,
      ymax: 85,
      spatialReference: {
        wkid: 4326
      }
    },
    esri: true
  }
  run('startups', options, 1, t)
})
```

where the 'startups' data is
```json
{"objectIdFieldName":"OBJECTID","globalIdFieldName":"","hasZ":false,"hasM":false,"geometryType":"esriGeometryPoint","spatialReference":{"wkid":4326},"fields":[{"name":"OBJECTID","type":"esriFieldTypeInteger","alias":"OBJECTID"},{"name":"COMPANY","type":"esriFieldTypeString","alias":"COMPANY","length":128},{"name":"AVATAR","type":"esriFieldTypeString","alias":"AVATAR","length":128}],"features":[{"attributes":{"OBJECTID":1,"COMPANY":"TEST","AVATAR":null},"geometry":{"x":8.6241263,"y":49.8707774}}]}
```

**Comment by tomtom92** [comment]
@mpayson @jgravois, I am taking a look at this issue now

**Comment by tomtom92** [comment]
Added @mpayson's `normalizeGeometry` fix as well as a more important one that converts an esri feature's geometry just before checking for an intersection. I have modified @mpayson's test & fixture to test a bit more. Since you mentioned you were using an older version of winnow, I'm not pushing to this PR.
The bug should be handled in v1.11.1
If there are still issues, I will reopen.

**Pull request closed without merging**
